Fix a docstring bug
Due to this unclosed code block, `cargo doc` will fail with:

error: Rust code block is empty
 --> src/lib.rs:9:5
  |
9 | //! ```
  |     ^^^

This patch fixes it.

Signed-off-by: Petr Horacek <hrck@protonmail.com>